import os
import sys
import logging
import stat
import yaml
from sqlalchemy import create_engine, Column, Integer, String, DateTime
from sqlalchemy.orm import sessionmaker, declarative_base
from crontab import CronTab

# --- Configuration & Logging ---

def load_config(config_path: str = "config.yaml") -> dict:
    if not os.path.exists(config_path):
        print(f"Error: {config_path} not found.")
        sys.exit(1)
    with open(config_path, "r") as f:
        return yaml.safe_load(f)

CONFIG = load_config()

# Setup logging
logging.basicConfig(
    filename=CONFIG["logging"]["file"],
    level=getattr(logging, CONFIG["logging"]["level"].upper(), logging.INFO),
    format='{"timestamp": "%(asctime)s", "level": "%(levelname)s", "component": "Manager", "message": "%(message)s"}'
)
logger = logging.getLogger("Manager")

# --- Database Setup (pipeline.db) ---

DATABASE_URL = CONFIG["database"]["pipeline_db_url"]
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(bind=engine)
Base = declarative_base()

class Source(Base):
    __tablename__ = "sources"
    id = Column(Integer, primary_key=True)
    url = Column(String, unique=True, nullable=False)
    source_type = Column(String, nullable=False)
    schedule = Column(String, nullable=False)
    last_scraped_at = Column(DateTime, nullable=True)

Base.metadata.create_all(engine)

# --- Wrapper Script Generation ---

SOURCE_COMMENT_MARKER = "ETL_PIPELINE_SOURCE"
TRANSFORMER_COMMENT_MARKER = "ETL_PIPELINE_TRANSFORMER"


def ensure_wrappers_exist():
    """
    Generates bash wrapper scripts that use 'uv run' to execute the python components.
    This ensures the cron environment matches the development environment.
    """
    project_root = CONFIG["system"].get("project_root", os.getcwd())
    uv_path = CONFIG["system"].get("uv_path", "uv") # Default to 'uv' if not set, but explicit path is safer for cron

    wrappers = {
        "run_extractor.sh": "src/news_weaver/extractor/extractor.py",
        "run_transformer.sh": "src/news_weaver/transformer/transformer.py"
    }

    generated_paths = {}

    for script_name, python_target in wrappers.items():
        wrapper_path = os.path.join(project_root, script_name)

        # We pass "$@" to forward arguments (like --source_id)
        # We redirect stdout/stderr inside the cron command, not here,
        # to keep the wrapper clean, but you could add it here too.
        bash_content = f"""#!/bin/bash
# Auto-generated by manager.py
cd {project_root}
{uv_path} run {python_target} "$@"
"""

        # Write file
        with open(wrapper_path, "w") as f:
            f.write(bash_content)

        # Make executable (chmod +x)
        st = os.stat(wrapper_path)
        os.chmod(wrapper_path, st.st_mode | stat.S_IEXEC)

        generated_paths[script_name] = wrapper_path
        logger.info(f"Verified/Created wrapper script: {wrapper_path}")

    return generated_paths

# --- Manager Logic ---

def update_crontab():
    session = SessionLocal()
    try:
        # 1. Ensure Bash Wrappers Exist
        wrappers = ensure_wrappers_exist()

        sources = session.query(Source).all()
        logger.info(f"Found {len(sources)} active sources to schedule.")

        cron = CronTab(user=True)

        # 2. Clear existing Pipeline jobs
        for job in list(cron):
            if job.comment == SOURCE_COMMENT_MARKER or job.comment == TRANSFORMER_COMMENT_MARKER:
                cron.remove(job)

        log_file = CONFIG['logging']['file']

        # 3. Schedule Extractor (via run_extractor.sh)
        # Bash command: /path/to/run_extractor.sh --source_id 123
        for source in sources:
            cmd = f"{wrappers['run_extractor.sh']} --source_id {source.id} >> {log_file} 2>&1"

            try:
                job = cron.new(command=cmd, comment=SOURCE_COMMENT_MARKER)
                job.setall(source.schedule)
                logger.info(f"Scheduled Source {source.id} ({source.url}) via bash wrapper.")
            except ValueError as e:
                logger.error(f"Invalid cron schedule for source {source.id}: {source.schedule}")

        # 4. Schedule Transformer (via run_transformer.sh)
        # Bash command: /path/to/run_transformer.sh
        trans_cmd = f"{wrappers['run_transformer.sh']} >> {log_file} 2>&1"
        transform_job = cron.new(command=trans_cmd, comment=TRANSFORMER_COMMENT_MARKER)
        transform_job.minute.every(5)
        logger.info("Scheduled Transformer (bash wrapper) to run every 5 minutes.")

        # 5. Commit
        cron.write()
        print(f"Crontab updated successfully. Wrappers created at {CONFIG['system']['project_root']}")

    except Exception as e:
        logger.error(f"Failed to update crontab: {e}")
        print(f"Error: {e}")
    finally:
        session.close()

if __name__ == "__main__":
    print("Synchronizing crontab...")
    update_crontab()
