"""Manager — reads schedules from the DB and synchronises the system crontab.

Uses SQLAlchemy 2.0 select() queries and pathlib for all path operations.
"""
import stat
from pathlib import Path

from crontab import CronTab
from sqlalchemy import select

from news_weaver.common.config import get_config, setup_logger
from news_weaver.common.database import PipelineSessionLocal, init_pipeline_db
from news_weaver.common.models import Source

logger = setup_logger("Manager")

# Comment markers used to identify auto-generated cron jobs
SOURCE_COMMENT_MARKER = "ETL_PIPELINE_SOURCE"
TRANSFORMER_COMMENT_MARKER = "ETL_PIPELINE_TRANSFORMER"


def ensure_wrappers_exist() -> dict[str, str]:
    """Generate (or refresh) the bash wrapper scripts used by cron."""
    cfg = get_config()
    project_root = Path(cfg.system.project_root).resolve()
    uv_path = cfg.system.uv_path

    wrappers = {
        "run_extractor.sh": "src/news_weaver/extractor.py",
        "run_transformer.sh": "src/news_weaver/transformer.py",
    }

    generated_paths: dict[str, str] = {}
    for script_name, python_target in wrappers.items():
        wrapper_path = project_root / script_name
        bash_content = (
            "#!/bin/bash\n"
            f"# Auto-generated by manager.py\n"
            f"cd {project_root}\n"
            f'{uv_path} run {python_target} "$@"\n'
        )
        wrapper_path.write_text(bash_content)
        # Make executable
        wrapper_path.chmod(wrapper_path.stat().st_mode | stat.S_IEXEC)
        generated_paths[script_name] = str(wrapper_path)
        logger.info(f"Verified wrapper: {wrapper_path}")

    return generated_paths


def update_crontab() -> None:
    """Sync the user's crontab with all active sources from the database."""
    init_pipeline_db()

    session = PipelineSessionLocal()
    try:
        wrappers = ensure_wrappers_exist()
        sources = list(session.execute(select(Source)).scalars())
        logger.info(f"Found {len(sources)} active sources.")

        cron = CronTab(user=True)

        # Remove previously generated jobs
        for job in list(cron):
            if job.comment in (SOURCE_COMMENT_MARKER, TRANSFORMER_COMMENT_MARKER):
                cron.remove(job)

        cfg = get_config()
        log_file = str(cfg.log_file_path)

        # Schedule one extractor job per source
        for source in sources:
            cmd = (
                f"{wrappers['run_extractor.sh']} --source_id {source.id}"
                f" >> {log_file} 2>&1"
            )
            try:
                job = cron.new(command=cmd, comment=SOURCE_COMMENT_MARKER)
                job.setall(source.schedule)
            except ValueError:
                logger.error(f"Invalid cron schedule for source {source.id}")

        # Schedule the transformer to run every 5 minutes
        trans_cmd = f"{wrappers['run_transformer.sh']} >> {log_file} 2>&1"
        transform_job = cron.new(command=trans_cmd, comment=TRANSFORMER_COMMENT_MARKER)
        transform_job.minute.every(5)

        cron.write()
        print("Crontab updated successfully.")

    except Exception as e:
        logger.error(f"Failed to update crontab: {e}")
    finally:
        session.close()


if __name__ == "__main__":
    update_crontab()
