import os
import stat
from crontab import CronTab

# Import Shared Logic
from news_weaver.common.config import CONFIG, setup_logger
from news_weaver.common.database import PipelineSessionLocal, init_pipeline_db
from news_weaver.common.models import Source

logger = setup_logger("Manager")

# Constants
SOURCE_COMMENT_MARKER = "ETL_PIPELINE_SOURCE"
TRANSFORMER_COMMENT_MARKER = "ETL_PIPELINE_TRANSFORMER"

def ensure_wrappers_exist():
    """Generates bash wrappers for Cron."""
    project_root = CONFIG["system"].get("project_root", os.getcwd())
    uv_path = CONFIG["system"].get("uv_path", "uv")

    # Updated paths to reflect package structure
    wrappers = {
        "run_extractor.sh": "src/news_weaver/extractor.py",
        "run_transformer.sh": "src/news_weaver/transformer.py"
    }

    generated_paths = {}
    for script_name, python_target in wrappers.items():
        wrapper_path = os.path.join(project_root, script_name)
        bash_content = f"""#!/bin/bash
# Auto-generated by manager.py
cd {project_root}
{uv_path} run {python_target} "$@"
"""
        with open(wrapper_path, "w") as f:
            f.write(bash_content)

        st = os.stat(wrapper_path)
        os.chmod(wrapper_path, st.st_mode | stat.S_IEXEC)
        generated_paths[script_name] = wrapper_path
        logger.info(f"Verified wrapper: {wrapper_path}")

    return generated_paths

def update_crontab():
    # Ensure DB tables exist
    init_pipeline_db()

    session = PipelineSessionLocal()
    try:
        wrappers = ensure_wrappers_exist()
        sources = session.query(Source).all()
        logger.info(f"Found {len(sources)} active sources.")

        cron = CronTab(user=True)

        # Clear existing jobs
        for job in list(cron):
            if job.comment in [SOURCE_COMMENT_MARKER, TRANSFORMER_COMMENT_MARKER]:
                cron.remove(job)

        log_file = CONFIG['logging']['file']

        # Schedule Extractors
        for source in sources:
            cmd = f"{wrappers['run_extractor.sh']} --source_id {source.id} >> {log_file} 2>&1"
            try:
                job = cron.new(command=cmd, comment=SOURCE_COMMENT_MARKER)
                job.setall(source.schedule)
            except ValueError:
                logger.error(f"Invalid schedule for source {source.id}")

        # Schedule Transformer
        trans_cmd = f"{wrappers['run_transformer.sh']} >> {log_file} 2>&1"
        transform_job = cron.new(command=trans_cmd, comment=TRANSFORMER_COMMENT_MARKER)
        transform_job.minute.every(5)

        cron.write()
        print("Crontab updated successfully.")

    except Exception as e:
        logger.error(f"Failed to update crontab: {e}")
    finally:
        session.close()

if __name__ == "__main__":
    update_crontab()
